theme: jekyll-theme-minimal
title: Test
description: test
exclude:
  - "License" # not applicative atm.
defaults:
  - scope:
      path: "example"
      values:
        title: "example"
        description: "example description"
        