name: Extracting Features From New Instances

on: 
  push:
    paths:
      - Resources/instances/*.col

jobs:
  extracting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        python-version: '3.9.13'

    - name: Install dependencies (if any)
      run: pip install -r requirements.txt || true

    - name: Extract features
      run: python feature_extractor.py
      working-directory: src/

    - name: Commit and Push Changes
      if: success()
      run: |
        git config --global user.name 'github-actions'
        git config --global user..email 'github-actions@github.com'
        git add Resources
        git commit -m "Updated InstanceFeatures.csv"
        git push
